server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    # Permitir archivos grandes (Ejemplo: 10 Gigabytes)
    client_max_body_size 10G;
    
    # Desactivar el buffering para subidas grandes (Mejora el rendimiento)
    fastcgi_request_buffering off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Seguridad: Bloquear acceso a carpetas sensibles
    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
    }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
    }

    # Ruta principal: Pasar todo a index.php
    location / {
        rewrite ^ /index.php$request_uri;
    }

    # Manejo de WebDAV (Arregla el error 405)
    location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|oc[ms]-provider/.+)\.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        try_files $fastcgi_script_name =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS off; # Como no usamos SSL todavía
        fastcgi_pass app:9000;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    # Activos estáticos
    location ~ \.(?:css|js|mjs|woff2?|svg|gif|map|otf)$ {
    types {
            text/css                css;
            text/javascript         js mjs;
            image/svg+xml           svg;
            application/wasm        wasm;
            font/woff2              woff2;
        }
    try_files $uri /index.php$request_uri;
    add_header Cache-Control "public, max-age=15778463";
    }

   


    location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap|mp4|webm)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=604800";
    }
}